pipeline {
    agent any

    stages {
        stage('Build') {
            agent {
                    label 'slave1'  //  using the slave1 machine/agent/node/slave for build stage
                }
                steps {
                
                    sh 'pwd'
                    sh 'sleep 10'
                    
            }
        }
        stage('Test') {
            
            steps {
                sh '''
                    #!/bin/bash
                    ls -lrt
                    sleep 10
                 '''   

            }

        }
    }   
}