pipeline {
    agent any

    stages {
        stage('Build') {
            agent {
                    label 'slave1'  //  using the slave1 machine/agent/node/slave for build stage
                }
                steps {
                
                    sh 'pwd'
                    sh 'sleep 10'
                    
            }
        }
        stage('Test') {
            
            steps {
                sh '''
                    #!/bin/bash
                    ls -lrt
                    sleep 10
                 '''   

            }

        }
    }
    post {
    success {
        
        // Send email notification when build succeeds
        emailext(
            subject: "Pipeline Success: ${env.JOB_NAME} [${env.BUILD_NUMBER}]",
            body: """The pipeline ${env.JOB_NAME} [${env.BUILD_NUMBER}] completed successfully.
            View details: ${env.BUILD_URL}""",
            to: '${env.EMAIL_RECIPIENTS},\$DEFAULT_RECIPIENTS' // Add your recipient email IDs here
        )
    }
    failure {
        // Send email notification when build fails
        emailext(
            subject: "Pipeline Failure: ${env.JOB_NAME} [${env.BUILD_NUMBER}]",
            body: """The pipeline ${env.JOB_NAME} [${env.BUILD_NUMBER}] failed.
            View details: ${env.BUILD_URL}""",
            to: 'nagaraju.aws456@gmail.com' // Add your recipient email IDs here
        )
    }
}

}