pipeline {
    agent none

    stages {
        stage('Build') {
            agent {
                    label 'slave1'  //  using the slave1 machine/agent/node/slave for build stage
                }
                steps {
                
                    sh '''
                    #!/bin/bash
                    cat Mavenfile
                    '''
            }
        }
        stage('Test') {
            agent any
            steps {
                sh '''
                    #!/bin/bash
                    ls -lrt
                    sleep 5
                 '''   

            }

        }
    }   
}