pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'sleep 5'
            }
        }

        stage('Test') {
            steps {
                sh '''
                    #!/bin/bash
                    ls -lrt
                    sleep 5
                 '''   

            }

        }
        stage('Trigger agent-1/Mavenfile Job') {
            steps {
                build job: 'agent-1/Mavenfile', wait: true
                echo 'agent-1/Mavenfile job triggered successfully!'
            }
        }
    }   
}
    