pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'sleep 5'
            }
        }

        stage('Test') {
            steps {
                sh '''
                    #!/bin/bash
                    ls -lrt
                    sleep 5
                 '''   

            }

        }
        stage('Trigger Maven-pipeline Job') {
            steps {
                build job: 'Maven-pipeline', wait: true
                echo 'Maven-pipeline job triggered successfully!'
            }
        }
    }   
}
    